// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_rolling_mean
NumericVector cpp_rolling_mean(NumericVector x, int window, int min_periods, bool skip_nan, int n_threads);
RcppExport SEXP _fastroll_cpp_rolling_mean(SEXP xSEXP, SEXP windowSEXP, SEXP min_periodsSEXP, SEXP skip_nanSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< bool >::type skip_nan(skip_nanSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_mean(x, window, min_periods, skip_nan, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_var
NumericVector cpp_rolling_var(NumericVector x, int window, int min_periods, int ddof, bool skip_nan, int n_threads);
RcppExport SEXP _fastroll_cpp_rolling_var(SEXP xSEXP, SEXP windowSEXP, SEXP min_periodsSEXP, SEXP ddofSEXP, SEXP skip_nanSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< int >::type ddof(ddofSEXP);
    Rcpp::traits::input_parameter< bool >::type skip_nan(skip_nanSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_var(x, window, min_periods, ddof, skip_nan, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_std
NumericVector cpp_rolling_std(NumericVector x, int window, int min_periods, int ddof, bool skip_nan, int n_threads);
RcppExport SEXP _fastroll_cpp_rolling_std(SEXP xSEXP, SEXP windowSEXP, SEXP min_periodsSEXP, SEXP ddofSEXP, SEXP skip_nanSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< int >::type ddof(ddofSEXP);
    Rcpp::traits::input_parameter< bool >::type skip_nan(skip_nanSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_std(x, window, min_periods, ddof, skip_nan, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_sum
NumericVector cpp_rolling_sum(NumericVector x, int window, int min_periods, bool skip_nan, int n_threads);
RcppExport SEXP _fastroll_cpp_rolling_sum(SEXP xSEXP, SEXP windowSEXP, SEXP min_periodsSEXP, SEXP skip_nanSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< bool >::type skip_nan(skip_nanSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_sum(x, window, min_periods, skip_nan, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_min
NumericVector cpp_rolling_min(NumericVector x, int window, int min_periods, bool skip_nan, int n_threads);
RcppExport SEXP _fastroll_cpp_rolling_min(SEXP xSEXP, SEXP windowSEXP, SEXP min_periodsSEXP, SEXP skip_nanSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< bool >::type skip_nan(skip_nanSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_min(x, window, min_periods, skip_nan, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_max
NumericVector cpp_rolling_max(NumericVector x, int window, int min_periods, bool skip_nan, int n_threads);
RcppExport SEXP _fastroll_cpp_rolling_max(SEXP xSEXP, SEXP windowSEXP, SEXP min_periodsSEXP, SEXP skip_nanSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< bool >::type skip_nan(skip_nanSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_max(x, window, min_periods, skip_nan, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_regression
List cpp_rolling_regression(NumericVector y, int window, int min_periods);
RcppExport SEXP _fastroll_cpp_rolling_regression(SEXP ySEXP, SEXP windowSEXP, SEXP min_periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_regression(y, window, min_periods));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_regression_xy
List cpp_rolling_regression_xy(NumericVector y, NumericVector x, int window, int min_periods);
RcppExport SEXP _fastroll_cpp_rolling_regression_xy(SEXP ySEXP, SEXP xSEXP, SEXP windowSEXP, SEXP min_periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_regression_xy(y, x, window, min_periods));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_multiple_regression
List cpp_rolling_multiple_regression(NumericVector y, NumericMatrix X, int window, int min_periods);
RcppExport SEXP _fastroll_cpp_rolling_multiple_regression(SEXP ySEXP, SEXP XSEXP, SEXP windowSEXP, SEXP min_periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_multiple_regression(y, X, window, min_periods));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_corr
List cpp_rolling_corr(NumericVector x, NumericVector y, int window, int min_periods, bool return_cov, bool skip_nan);
RcppExport SEXP _fastroll_cpp_rolling_corr(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP min_periodsSEXP, SEXP return_covSEXP, SEXP skip_nanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< bool >::type return_cov(return_covSEXP);
    Rcpp::traits::input_parameter< bool >::type skip_nan(skip_nanSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_corr(x, y, window, min_periods, return_cov, skip_nan));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_cov
NumericVector cpp_rolling_cov(NumericVector x, NumericVector y, int window, int min_periods, int ddof, bool skip_nan);
RcppExport SEXP _fastroll_cpp_rolling_cov(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP min_periodsSEXP, SEXP ddofSEXP, SEXP skip_nanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< int >::type ddof(ddofSEXP);
    Rcpp::traits::input_parameter< bool >::type skip_nan(skip_nanSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_cov(x, y, window, min_periods, ddof, skip_nan));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_corr_matrix
NumericVector cpp_rolling_corr_matrix(NumericMatrix X, int window, int min_periods, int n_threads);
RcppExport SEXP _fastroll_cpp_rolling_corr_matrix(SEXP XSEXP, SEXP windowSEXP, SEXP min_periodsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_corr_matrix(X, window, min_periods, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_skew
NumericVector cpp_rolling_skew(NumericVector x, int window, int min_periods, bool skip_nan);
RcppExport SEXP _fastroll_cpp_rolling_skew(SEXP xSEXP, SEXP windowSEXP, SEXP min_periodsSEXP, SEXP skip_nanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< bool >::type skip_nan(skip_nanSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_skew(x, window, min_periods, skip_nan));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_kurt
NumericVector cpp_rolling_kurt(NumericVector x, int window, int min_periods, bool skip_nan);
RcppExport SEXP _fastroll_cpp_rolling_kurt(SEXP xSEXP, SEXP windowSEXP, SEXP min_periodsSEXP, SEXP skip_nanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< bool >::type skip_nan(skip_nanSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_kurt(x, window, min_periods, skip_nan));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_zscore
NumericVector cpp_rolling_zscore(NumericVector x, int window, int min_periods, int ddof, bool skip_nan, int n_threads);
RcppExport SEXP _fastroll_cpp_rolling_zscore(SEXP xSEXP, SEXP windowSEXP, SEXP min_periodsSEXP, SEXP ddofSEXP, SEXP skip_nanSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< int >::type ddof(ddofSEXP);
    Rcpp::traits::input_parameter< bool >::type skip_nan(skip_nanSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_zscore(x, window, min_periods, ddof, skip_nan, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_quantile
NumericVector cpp_rolling_quantile(NumericVector x, int window, double q, int min_periods, bool exact);
RcppExport SEXP _fastroll_cpp_rolling_quantile(SEXP xSEXP, SEXP windowSEXP, SEXP qSEXP, SEXP min_periodsSEXP, SEXP exactSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< bool >::type exact(exactSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_quantile(x, window, q, min_periods, exact));
    return rcpp_result_gen;
END_RCPP
}
// cpp_expanding_mean
NumericVector cpp_expanding_mean(NumericVector x, int min_periods);
RcppExport SEXP _fastroll_cpp_expanding_mean(SEXP xSEXP, SEXP min_periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_expanding_mean(x, min_periods));
    return rcpp_result_gen;
END_RCPP
}
// cpp_expanding_var
NumericVector cpp_expanding_var(NumericVector x, int min_periods, int ddof);
RcppExport SEXP _fastroll_cpp_expanding_var(SEXP xSEXP, SEXP min_periodsSEXP, SEXP ddofSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< int >::type ddof(ddofSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_expanding_var(x, min_periods, ddof));
    return rcpp_result_gen;
END_RCPP
}
// cpp_expanding_std
NumericVector cpp_expanding_std(NumericVector x, int min_periods, int ddof);
RcppExport SEXP _fastroll_cpp_expanding_std(SEXP xSEXP, SEXP min_periodsSEXP, SEXP ddofSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< int >::type ddof(ddofSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_expanding_std(x, min_periods, ddof));
    return rcpp_result_gen;
END_RCPP
}
// cpp_expanding_sum
NumericVector cpp_expanding_sum(NumericVector x, int min_periods);
RcppExport SEXP _fastroll_cpp_expanding_sum(SEXP xSEXP, SEXP min_periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_expanding_sum(x, min_periods));
    return rcpp_result_gen;
END_RCPP
}
// cpp_expanding_regression
List cpp_expanding_regression(NumericVector y, int min_periods);
RcppExport SEXP _fastroll_cpp_expanding_regression(SEXP ySEXP, SEXP min_periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_expanding_regression(y, min_periods));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_mean_matrix
NumericMatrix cpp_rolling_mean_matrix(NumericMatrix X, int window, int min_periods, int n_threads);
RcppExport SEXP _fastroll_cpp_rolling_mean_matrix(SEXP XSEXP, SEXP windowSEXP, SEXP min_periodsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_mean_matrix(X, window, min_periods, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_std_matrix
NumericMatrix cpp_rolling_std_matrix(NumericMatrix X, int window, int min_periods, int ddof, int n_threads);
RcppExport SEXP _fastroll_cpp_rolling_std_matrix(SEXP XSEXP, SEXP windowSEXP, SEXP min_periodsSEXP, SEXP ddofSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< int >::type ddof(ddofSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_std_matrix(X, window, min_periods, ddof, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_sum_matrix
NumericMatrix cpp_rolling_sum_matrix(NumericMatrix X, int window, int min_periods, int n_threads);
RcppExport SEXP _fastroll_cpp_rolling_sum_matrix(SEXP XSEXP, SEXP windowSEXP, SEXP min_periodsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_sum_matrix(X, window, min_periods, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_min_matrix
NumericMatrix cpp_rolling_min_matrix(NumericMatrix X, int window, int min_periods, bool skip_nan, int n_threads);
RcppExport SEXP _fastroll_cpp_rolling_min_matrix(SEXP XSEXP, SEXP windowSEXP, SEXP min_periodsSEXP, SEXP skip_nanSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< bool >::type skip_nan(skip_nanSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_min_matrix(X, window, min_periods, skip_nan, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_max_matrix
NumericMatrix cpp_rolling_max_matrix(NumericMatrix X, int window, int min_periods, bool skip_nan, int n_threads);
RcppExport SEXP _fastroll_cpp_rolling_max_matrix(SEXP XSEXP, SEXP windowSEXP, SEXP min_periodsSEXP, SEXP skip_nanSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    Rcpp::traits::input_parameter< bool >::type skip_nan(skip_nanSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_max_matrix(X, window, min_periods, skip_nan, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rolling_spearman
NumericVector cpp_rolling_spearman(NumericVector x, NumericVector y, int window, int min_periods);
RcppExport SEXP _fastroll_cpp_rolling_spearman(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP min_periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type min_periods(min_periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rolling_spearman(x, y, window, min_periods));
    return rcpp_result_gen;
END_RCPP
}
// cpp_set_num_threads
void cpp_set_num_threads(int n);
RcppExport SEXP _fastroll_cpp_set_num_threads(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    cpp_set_num_threads(n);
    return R_NilValue;
END_RCPP
}
// cpp_get_num_threads
int cpp_get_num_threads();
RcppExport SEXP _fastroll_cpp_get_num_threads() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_get_num_threads());
    return rcpp_result_gen;
END_RCPP
}
// cpp_has_avx2
bool cpp_has_avx2();
RcppExport SEXP _fastroll_cpp_has_avx2() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_has_avx2());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastroll_cpp_rolling_mean", (DL_FUNC) &_fastroll_cpp_rolling_mean, 5},
    {"_fastroll_cpp_rolling_var", (DL_FUNC) &_fastroll_cpp_rolling_var, 6},
    {"_fastroll_cpp_rolling_std", (DL_FUNC) &_fastroll_cpp_rolling_std, 6},
    {"_fastroll_cpp_rolling_sum", (DL_FUNC) &_fastroll_cpp_rolling_sum, 5},
    {"_fastroll_cpp_rolling_min", (DL_FUNC) &_fastroll_cpp_rolling_min, 5},
    {"_fastroll_cpp_rolling_max", (DL_FUNC) &_fastroll_cpp_rolling_max, 5},
    {"_fastroll_cpp_rolling_regression", (DL_FUNC) &_fastroll_cpp_rolling_regression, 3},
    {"_fastroll_cpp_rolling_regression_xy", (DL_FUNC) &_fastroll_cpp_rolling_regression_xy, 4},
    {"_fastroll_cpp_rolling_multiple_regression", (DL_FUNC) &_fastroll_cpp_rolling_multiple_regression, 4},
    {"_fastroll_cpp_rolling_corr", (DL_FUNC) &_fastroll_cpp_rolling_corr, 6},
    {"_fastroll_cpp_rolling_cov", (DL_FUNC) &_fastroll_cpp_rolling_cov, 6},
    {"_fastroll_cpp_rolling_corr_matrix", (DL_FUNC) &_fastroll_cpp_rolling_corr_matrix, 4},
    {"_fastroll_cpp_rolling_skew", (DL_FUNC) &_fastroll_cpp_rolling_skew, 4},
    {"_fastroll_cpp_rolling_kurt", (DL_FUNC) &_fastroll_cpp_rolling_kurt, 4},
    {"_fastroll_cpp_rolling_zscore", (DL_FUNC) &_fastroll_cpp_rolling_zscore, 6},
    {"_fastroll_cpp_rolling_quantile", (DL_FUNC) &_fastroll_cpp_rolling_quantile, 5},
    {"_fastroll_cpp_expanding_mean", (DL_FUNC) &_fastroll_cpp_expanding_mean, 2},
    {"_fastroll_cpp_expanding_var", (DL_FUNC) &_fastroll_cpp_expanding_var, 3},
    {"_fastroll_cpp_expanding_std", (DL_FUNC) &_fastroll_cpp_expanding_std, 3},
    {"_fastroll_cpp_expanding_sum", (DL_FUNC) &_fastroll_cpp_expanding_sum, 2},
    {"_fastroll_cpp_expanding_regression", (DL_FUNC) &_fastroll_cpp_expanding_regression, 2},
    {"_fastroll_cpp_rolling_mean_matrix", (DL_FUNC) &_fastroll_cpp_rolling_mean_matrix, 4},
    {"_fastroll_cpp_rolling_std_matrix", (DL_FUNC) &_fastroll_cpp_rolling_std_matrix, 5},
    {"_fastroll_cpp_rolling_sum_matrix", (DL_FUNC) &_fastroll_cpp_rolling_sum_matrix, 4},
    {"_fastroll_cpp_rolling_min_matrix", (DL_FUNC) &_fastroll_cpp_rolling_min_matrix, 5},
    {"_fastroll_cpp_rolling_max_matrix", (DL_FUNC) &_fastroll_cpp_rolling_max_matrix, 5},
    {"_fastroll_cpp_rolling_spearman", (DL_FUNC) &_fastroll_cpp_rolling_spearman, 4},
    {"_fastroll_cpp_set_num_threads", (DL_FUNC) &_fastroll_cpp_set_num_threads, 1},
    {"_fastroll_cpp_get_num_threads", (DL_FUNC) &_fastroll_cpp_get_num_threads, 0},
    {"_fastroll_cpp_has_avx2", (DL_FUNC) &_fastroll_cpp_has_avx2, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastroll(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
