# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_rolling_mean <- function(x, window, min_periods, skip_nan, n_threads) {
    .Call(`_fastroll_cpp_rolling_mean`, x, window, min_periods, skip_nan, n_threads)
}

cpp_rolling_var <- function(x, window, min_periods, ddof, skip_nan, n_threads) {
    .Call(`_fastroll_cpp_rolling_var`, x, window, min_periods, ddof, skip_nan, n_threads)
}

cpp_rolling_std <- function(x, window, min_periods, ddof, skip_nan, n_threads) {
    .Call(`_fastroll_cpp_rolling_std`, x, window, min_periods, ddof, skip_nan, n_threads)
}

cpp_rolling_sum <- function(x, window, min_periods, skip_nan, n_threads) {
    .Call(`_fastroll_cpp_rolling_sum`, x, window, min_periods, skip_nan, n_threads)
}

cpp_rolling_min <- function(x, window, min_periods, skip_nan, n_threads) {
    .Call(`_fastroll_cpp_rolling_min`, x, window, min_periods, skip_nan, n_threads)
}

cpp_rolling_max <- function(x, window, min_periods, skip_nan, n_threads) {
    .Call(`_fastroll_cpp_rolling_max`, x, window, min_periods, skip_nan, n_threads)
}

cpp_rolling_regression <- function(y, window, min_periods) {
    .Call(`_fastroll_cpp_rolling_regression`, y, window, min_periods)
}

cpp_rolling_regression_xy <- function(y, x, window, min_periods) {
    .Call(`_fastroll_cpp_rolling_regression_xy`, y, x, window, min_periods)
}

cpp_rolling_multiple_regression <- function(y, X, window, min_periods) {
    .Call(`_fastroll_cpp_rolling_multiple_regression`, y, X, window, min_periods)
}

cpp_rolling_corr <- function(x, y, window, min_periods, return_cov, skip_nan) {
    .Call(`_fastroll_cpp_rolling_corr`, x, y, window, min_periods, return_cov, skip_nan)
}

cpp_rolling_cov <- function(x, y, window, min_periods, ddof, skip_nan) {
    .Call(`_fastroll_cpp_rolling_cov`, x, y, window, min_periods, ddof, skip_nan)
}

cpp_rolling_corr_pairs <- function(X, window, min_periods, n_threads) {
    .Call(`_fastroll_cpp_rolling_corr_pairs`, X, window, min_periods, n_threads)
}

cpp_rolling_corr_matrix <- function(X, window, min_periods, n_threads) {
    .Call(`_fastroll_cpp_rolling_corr_matrix`, X, window, min_periods, n_threads)
}

cpp_rolling_skew <- function(x, window, min_periods, skip_nan) {
    .Call(`_fastroll_cpp_rolling_skew`, x, window, min_periods, skip_nan)
}

cpp_rolling_kurt <- function(x, window, min_periods, skip_nan) {
    .Call(`_fastroll_cpp_rolling_kurt`, x, window, min_periods, skip_nan)
}

cpp_rolling_zscore <- function(x, window, min_periods, ddof, skip_nan, n_threads) {
    .Call(`_fastroll_cpp_rolling_zscore`, x, window, min_periods, ddof, skip_nan, n_threads)
}

cpp_rolling_quantile <- function(x, window, q, min_periods, exact) {
    .Call(`_fastroll_cpp_rolling_quantile`, x, window, q, min_periods, exact)
}

cpp_expanding_quantile_approx <- function(x, q, min_periods) {
    .Call(`_fastroll_cpp_expanding_quantile_approx`, x, q, min_periods)
}

cpp_expanding_mean <- function(x, min_periods) {
    .Call(`_fastroll_cpp_expanding_mean`, x, min_periods)
}

cpp_expanding_var <- function(x, min_periods, ddof) {
    .Call(`_fastroll_cpp_expanding_var`, x, min_periods, ddof)
}

cpp_expanding_std <- function(x, min_periods, ddof) {
    .Call(`_fastroll_cpp_expanding_std`, x, min_periods, ddof)
}

cpp_expanding_sum <- function(x, min_periods) {
    .Call(`_fastroll_cpp_expanding_sum`, x, min_periods)
}

cpp_expanding_regression <- function(y, min_periods) {
    .Call(`_fastroll_cpp_expanding_regression`, y, min_periods)
}

cpp_rolling_mean_matrix <- function(X, window, min_periods, n_threads) {
    .Call(`_fastroll_cpp_rolling_mean_matrix`, X, window, min_periods, n_threads)
}

cpp_rolling_std_matrix <- function(X, window, min_periods, ddof, n_threads) {
    .Call(`_fastroll_cpp_rolling_std_matrix`, X, window, min_periods, ddof, n_threads)
}

cpp_rolling_sum_matrix <- function(X, window, min_periods, n_threads) {
    .Call(`_fastroll_cpp_rolling_sum_matrix`, X, window, min_periods, n_threads)
}

cpp_rolling_min_matrix <- function(X, window, min_periods, skip_nan, n_threads) {
    .Call(`_fastroll_cpp_rolling_min_matrix`, X, window, min_periods, skip_nan, n_threads)
}

cpp_rolling_max_matrix <- function(X, window, min_periods, skip_nan, n_threads) {
    .Call(`_fastroll_cpp_rolling_max_matrix`, X, window, min_periods, skip_nan, n_threads)
}

cpp_rolling_spearman <- function(x, y, window, min_periods) {
    .Call(`_fastroll_cpp_rolling_spearman`, x, y, window, min_periods)
}

cpp_set_num_threads <- function(n) {
    invisible(.Call(`_fastroll_cpp_set_num_threads`, n))
}

cpp_get_num_threads <- function() {
    .Call(`_fastroll_cpp_get_num_threads`)
}

cpp_has_avx2 <- function() {
    .Call(`_fastroll_cpp_has_avx2`)
}

